/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/views/error-page/404.vue')['default']
    AppContent: typeof import('./src/layout/component/AppContent.vue')['default']
    Dashboard: typeof import('./src/views/dashboard/index.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Navbar: typeof import('./src/layout/component/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/layout/component/sidebar/index.vue')['default']
    Test: typeof import('./src/views/test/index.vue')['default']
  }
}
