/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../views/error-page/404.vue')['default']
    AppContent: typeof import('./../layout/component/AppContent.vue')['default']
    Dashboard: typeof import('./../views/dashboard/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    Layout: typeof import('./../layout/index.vue')['default']
    Login: typeof import('./../views/login/index.vue')['default']
    Navbar: typeof import('./../layout/component/navbar/index.vue')['default']
    NavigateLink: typeof import('./../layout/component/sidebar/NavigateLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../layout/component/sidebar/index.vue')['default']
    SidebarItem: typeof import('./../layout/component/sidebar/sidebarItem.vue')['default']
    Test: typeof import('./../views/test/index.vue')['default']
  }
}
